name: Link Check
on:
  push:
    branches: [ main, docs-and-ci-setup ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          # Check all markdown files in docs/ and README.md
          args: --config .github/lychee.toml --verbose --no-progress --exclude-loopback --exclude-private --exclude-mail --accept 200,204,429 'README.md' 'docs/**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
